### ISSUE TITLE
rename "data/maps" folder

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#122]
This is a small issue, but resolving it may reduce confusion for people learning the system. The  [public/data/maps folder](https://github.com/ebimodeling/ghgvc/tree/master/public/data/maps) does not actually contain maps, just a series of .csv files that guide classification of ecosystem types and assigning of default values. Let's rename it something like "ecosystem_definitions_and_defaults" (also need to fix the code).

**Comment by teixeirak** [comment]
Related to this, at least some of the files in the main public/data/ folder are out of date (6 yrs old). Are any of them actually used? If not, we should delete or at least move to some "archive" folder to avoid confusing.

**Comment by teixeirak** [comment]
I deleted some outdated files in [this commit](https://github.com/ebimodeling/ghgvc/commit/8bd404225c2675a1c01633aed2692db3e6639b78). I think there are a couple others that are no longer used, but not sure.

**Comment by caseyhofford** [comment]
Unfortunately only removing the files seems to break the app :/. I think this is mostly due to old code referencing these files.
So for now, the files in public/data are still technically being used by the rails app, though it seems like they don't have any real purpose. There are some global variables created that use these files, but it doesn't seem that the application uses these variables after they are set.
I will see if it is simple to remove references to these files from the code.

**Comment by teixeirak** [comment]
Okay, thanks for fixing that.

**Comment by caseyhofford** [comment]
It was actually pretty easy to remove the references to the remaining files! I think I can also remove calculator.js and variable_db.json without any issues.

**Comment by teixeirak** [comment]
Great! Yes, please do remove those others. 

And, if its not too complicated, it would be great to move the files in "maps" up into "data" and delete "maps".

**Comment by caseyhofford** [comment]
OK, I think all of this data has moved into the app_data.zip file that is downloaded by running 'download-netcdf.sh' when the application is first run. This means we could probably remove the whole /maps folder, since the zip file will just recreate these files. I am testing to make sure this will work now.
That zip file needs to be moved to a new hosting option. It is [no longer available at the dropbox link](https://www.dropbox.com/s/2g2x58fkolgnn76/app_data.zip?dl=1) I have added an issue for this #137

**Comment by teixeirak** [comment]
> This means we could probably remove the whole /maps folder

What about the .csv files that are currently in  /maps? Those should live on GitHub for easy editing.

**Comment by caseyhofford** [comment]
OK, it looks like I was wrong, the /data folder for ghgvc is not shared with the /data folder for ghgvcR. 
However, those CSV files exist both in this GitHub repo and in the Zip file. This could be an issue if they are edited here but not in the zip file. I am a little unclear on when the application uses data stored in the ghgvc repository and when it uses data from the zip file. It seems like at one point the ghgvc repository did all the work and had all the data, because there are R scripts duplicated from ghgvcR in this repository as well. Is it possible none of the /data folder is used, and this is all handled by the ghgvcR app now?

**Comment by teixeirak** [comment]
I have no idea. @dlebauer, can you answer this?

We definitely want the master version of the .csv files on GitHub for easy editing and version history.

**Comment by dlebauer** [comment]
Sorry I am confused - I agree that there should be only one copy of the data and github is a good place for csv files. But it is not clear what the question is - I don't see a /data directory in the ghgvcR repository  https://github.com/ebimodeling/ghgvcR ?

**Comment by teixeirak** [comment]
This is the directory in question: https://github.com/ebimodeling/ghgvc/tree/master/public/data. The .csv files are currently in the /maps folder of this directory (which makes no sense in terms of naming!). Can we confirm that the code is reading those?

**Comment by dlebauer** [comment]
ghgvcR reads in the four csv files in data/maps here: https://github.com/ebimodeling/ghgvcR/blob/95b0186d388e515458a0953fb04378b54c564817/R/biome.R#L281

It is possible but unlikely (I haven't looked much since the refactoring and dockerization) that the download script puts another copy of these into a folder called data/maps that is then mounted to the docker container. My suggestion is to remove them from the zip file and make sure that the app is using the ones in the repository. 

Does that answer your question?

**Comment by caseyhofford** [comment]
I think the dockerization may have messed this up. From my testing, the code in biome.R is not impacted by changes to the 'data' directory in ghgvc. It finds those files in the Docker volume 'netcdf-data' which is populated in the [download-netcdf.sh script](https://github.com/ebimodeling/ghgvcR/blob/06aac5d6b66b431e5c8bd61b56a944980c74d733/download-netcdf.sh#L4). The [unzip -o](https://github.com/ebimodeling/ghgvcR/blob/06aac5d6b66b431e5c8bd61b56a944980c74d733/download-netcdf.sh#L6) will overwrite any existing directory and the [check for `/app/data/name_indexed_ecosystems.json`](https://github.com/ebimodeling/ghgvcR/blob/06aac5d6b66b431e5c8bd61b56a944980c74d733/download-netcdf.sh#L4) make me think all these files came from the zip, not the github repo.

The rails app doesn't seem to need these files either. The [calculator.js script does create variables from them](https://github.com/ebimodeling/ghgvc/blob/8bd404225c2675a1c01633aed2692db3e6639b78/app/assets/javascripts/calculator.js#L41), but they are never used.

What would you think of moving these files permanently into the ghgvcR repository at ghgvcR/data? We can then change the download-netcdf.sh script to only populate data in /data/netcdf. This feels like a natural place for them since the data is needed by R, not the ruby app.

Sorry if I'm explaining this poorly, or misunderstanding. I think I am getting a little confused about what work the rails app is actually responsible for. I have been thinking of it as just a frontend to pass and select data to and from the Rserve app. Am I right in assuming that there should be minimal calculations or data manipulation happening in the rails project?

**Comment by teixeirak** [comment]
> What would you think of moving these files permanently into the ghgvcR repository at ghgvcR/data?

This seems to make sense, although my understanding of the structure is limited. If it works, please do it.

> Sorry if I'm explaining this poorly, or misunderstanding. I think I am getting a little confused about what work the rails app is actually responsible for. I have been thinking of it as just a frontend to pass and select data to and from the Rserve app. Am I right in assuming that there should be minimal calculations or data manipulation happening in the rails project?

Unfortunately I can't answer this. @dlebauer?

**Comment by dlebauer** [comment]
Yes I think all calculations should be done by the R package.

**Comment by teixeirak** [comment]
@caseyhofford, FYI I have built a [Matlab script ](https://github.com/teixeirak/ghgvc_KAT/blob/master/scripts/biomass_defaults_update.m) to update biome_defaults.csv (in its current location, but can easily change that).

**Comment by caseyhofford** [comment]
@teixeirak I have moved the biome_defaults.csv to ghgvcr/data along with the other csvs. Once that PR is approved we can track the changes there instead. I don't think there is a way to maintain the history after moving these files between repositories, but that shouldn't be a problem.

**Comment by teixeirak** [comment]
Thanks, @caseyhofford !
