### ISSUE TITLE
Fixes to user-downloadable CSV file.

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#55]
The .csv file needs two minor fixes:
1) include latitude, longitude
2) include units in column headers. Units for all are:  [Mg CO2-eq ha-1 X yrs-1], where X =T_A.

**Comment by potterzot** [comment]
lat/lon is added to the csv file, but I wanted to check on the units - do you really want each header name to have the units in the name? It currently looks like:

Location | Biome | lat | lng | S_CO2 | S_CH4 | ...
--- | --- | --- | --- | --- | --- | ---
1 | "scrub/woodland" | 38 | -97.1 | 271.1 | 2.3 | ...
2 | "temperate cropland" | 38 | -97.1 | 20.3 | 0.6 | ...

But adding the units would look like:

Location | Biome | lat | lng | S_CO2 [Mg CO2-eq ha-1 50 yrs-1] | S_CH4 [Mg CO2-eq ha-1 50 yrs-1] | ...
--- | --- | --- | --- | --- | --- | ---
1 | "scrub/woodland" | 38 | -97.1 | 271.1 | 2.3 | ...
2 | "temperate cropland" | 38 | -97.1 | 20.3 | 0.6 | ...

If all the units are the same, I would suggest maybe adding a separate single column line at the bottom of the csv so that it looks like:

Location | Biome | lat | lng | S_CO2 | S_CH4 | ...
--- | --- | --- | --- | --- | --- | ---
1 | "scrub/woodland" | 38 | -97.1 | 271.1 | 2.3 | ...
2 | "temperate cropland" | 38 | -97.1 | 20.3 | 0.6 | ...
Units: [Mg CO2-eq ha-1 50 yrs-1] | | | | | |

Of course however you'd like I'll do, I just thought maybe this would be better.

**Comment by teixeirak** [comment]
Let's keep the units in each column. This file is intended to be more functional than attractive, and it's better practice to have the units with the variable name. It does not need to be formatted with adjusted column width, bold headers, etc.; just leave as a .csv format.

Thanks!

On Aug 3, 2016, at 11:36 PM, Nicholas Potter <notifications@github.com<mailto:notifications@github.com>> wrote:


lat/lon is added to the csv file, but I wanted to check on the units - do you really want each header name to have the units in the name? It currently looks like:

Location        Biome   lat     lng     S_CO2   S_CH4   ...
1       "scrub/woodland"        38      -97.1   271.1   2.3     ...
2       "temperate cropland"    38      -97.1   20.3    0.6     ...

But adding the units would look like:

Location        Biome   lat     lng     S_CO2 [Mg CO2-eq ha-1 50 yrs-1] S_CH4 [Mg CO2-eq ha-1 50 yrs-1] ...
1       "scrub/woodland"        38      -97.1   271.1   2.3     ...
2       "temperate cropland"    38      -97.1   20.3    0.6     ...

If all the units are the same, I would suggest maybe adding a separate single column line at the bottom of the csv so that it looks like:

Location        Biome   lat     lng     S_CO2   S_CH4   ...
1       "scrub/woodland"        38      -97.1   271.1   2.3     ...
2       "temperate cropland"    38      -97.1   20.3    0.6     ...
Units: [Mg CO2-eq ha-1 50 yrs-1]

Of course however you'd like I'll do, I just thought maybe this would be better.

**Comment by potterzot** [comment]
Done.
