### ISSUE TITLE
incorrect plotting of GHGV terms

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#56]
When I run tropical pasture, v sugarcane, v soy, all come up with negative
storage. All storage be positive.
It looks like the storage and flux terms are switched on the graph.  If
you download the csv file, they're correct.  Interestingly, they are also
correct if tropical forest is checked, which must mean the plotting is
done differently depending on if a native ecosystem is included..

**Comment by dlebauer** [comment]
Example: 

![image](https://cloud.githubusercontent.com/assets/464871/7774525/ad5b5120-0071-11e5-8a5c-a437a708100f.png)

csv is here: https://gist.github.com/dlebauer/0fc5a16c963d9d9715bb

**Comment by dlebauer** [comment]
Two more issues

1. when I select only one ecosystem, the plot is squashed and no bars are apparent
2. when I select > 1 ecosystem at one or more sites, the results are the results of previous run that worked correctly.

**Comment by dlebauer** [comment]
Here is a figure of squashed figure from 1 above

<img width="969" alt="screen shot 2016-07-26 at 5 28 26 pm" src="https://cloud.githubusercontent.com/assets/464871/17156174/6b09392a-5356-11e6-90c9-bcf5fc52b87d.png">

**Comment by potterzot** [comment]
Moving the below to a separate issue since it's unrelated:

> 1. when I select only one ecosystem, the plot is squashed and no bars are apparent

That leaves this bug about the following probably related things:

1. When select >1 site or an ag site, app crashes (was loads previous data, but that is fixed)
2. When I run tropical pasture, v sugarcane, v soy, all come up with negative storage. All storage should be positive.
3. It looks like the storage and flux terms are switched on the graph. If you download the csv file, they're correct. Interestingly, they are also correct if tropical forest is checked, which must mean the plotting is
done differently depending on if a native ecosystem is included..

**Comment by potterzot** [comment]
The below are fixed, 3 is remaining.

~~1) When select >1 site or an ag site, app crashes (was loads previous data, but that is fixed).~~
~~2) When I run tropical pasture, v sugarcane, v soy, all come up with negative storage. All storage should be positive.~~

3) It looks like the storage and flux terms are switched on the graph. If you download the csv file, they're correct. Interestingly, they are also correct if tropical forest is checked, which must mean the plotting is done differently depending on if a native ecosystem is included..

Plotting was done differently because the agroecosystems lack latent and sw_radiative_forcing, which were not being correctly set to 0. This was causing an error and drop back to old version of plotting.

**Comment by potterzot** [comment]
Looks like (3) above was an artifact of ggplot2. negative Ongoing Exchange values were overlaid on top of the Storage bars, and then the labelling was switched. ggplot2 emits a warning that it doesn't play well with negative y values, so I suspect that's part of why.

Anyway, was able to code around it so that it plots correctly now.
