### ISSUE TITLE
Identify and load additional maps

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#65]
Maps that we have already identified as potentially interesting include the following:

- [ ] US biomass map from FIA (we have had trouble with this in the past): http://www.whrc.org/mapping/nbcd/
- [ ] Canada biomass map
- [ ] (Baccini et al., 2012) tropical biomass map, available here: http://www.arcgis.com/home/item.html?id=2332b43bc5454127bfde21e894c89a51 
- [ ] other regional biomass maps, if accessible
- [ ] model intercomparison maps (global- David mentioned these)
- [ ] Almut & Anita's global GHGV map or components thereof (modeled in LPJ, Evan reviewed this paper.)
- [ ] new map from Peter Snyder of biophysical values for pasture and maybe generic cropland, if he is able/willing to run those.

**Comment by dlebauer** [comment]
@ValentineHerr 

Here is an example of how you can compute the average of a variable over time. For the CLM TotLivBiom.nc. [Install NCO](http://nco.sourceforge.net/) and do:

```
ncwa -O -C -a time -y avg CLM4_RG1_Monthly_TotLivBiom.nc4 CLM4_RG1_TotLivBiom.nc4  
```

**Comment by ValentineHerr** [comment]
@dlebauer 
Sorry it took me a while to get to this (field + waiting for admin password to install NCO)
If it is easy for you, could you tel me how to set the directory of input and output files for the command? I've tried to look at the manual and understand the commands but I am not making a lot of progress and I only need to run the command you gave me so I figured asking you would be faster

**Comment by dlebauer** [comment]
@hmb1 I have a few questions:

1) Starting with a file of monthly values over 110 years (e.g. this [250MB file of NEE](https://uofi.box.com/s/owvtjedivps4yhmlebgk0ooflz2ef6k2), how can we compute the annual sums and then compute the average over years (analagous to a 'climatology' variable like mean annual temperature)?

I've been trying to compute the annual sums like `ncra -O -F -d time,1,1340,12 -y ttl in.nc out.nc` but get

> ncra: ERROR no variables fit criteria for processing
> ncra Hint Extraction list must contain a record variable that is not NC_CHAR or NC_STRING

however the TotLivBiom variable is a float ...?

If I use `ncwa -O -C -a time,1,1340,12 -y ttl in.nc out.nc` it creates a file that sums over the record dimension rather than each 12 months. 

2) Have you ever seen the error 

> $ ncwa -O -C -a time -y avg CLM4_RG1_Monthly_TotLivBiom.nc4 CLM4_RG1_TotLivBiom.nc4
ncwa: ERROR nco_malloc_flg() unable to allocate 1368576000 B = 1336500 kB = 1305 MB = 1 GB
ncwa: malloc() error is "Not enough space"
ncwa: ERROR Unable to malloc() 342144000*4 bytes for value buffer for variable TotLivBiom in main()

and is there a way to fix it (memory settings)?

**Comment by teixeirak** [comment]
This is now covered by #86. Closing this issue.
