### ISSUE TITLE
Graphing problem, detected 12/31/15

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#72]
I just detected a graphing problem; no values are appearing on the graph, as in the attached image. I'm seeing this on a Mac- both Firefox and Safari.

![untitled](https://cloud.githubusercontent.com/assets/6355854/12065977/63997016-afae-11e5-9195-b1da81a45c18.png)

**Comment by dlebauer** [comment]
I just reproduced the issue. 

## What works: 

* The .csv file is generated, and has sensible values for tropical forests
* other ecosystems work. When I select a site with Tropical forests and crops as options, the bars for the other ecosystems show up, but the tropical forest system does not.

## What doesn't work:

* Although the csv file has the required values, the bar on the plot is not printed for tropical forests. 

## Conclusions:

I am not sure when the last time the calculator worked for tropical forests. The live version has not been updated for over a year (it is on 31356cbfbbf5c7e2d254ccda19fb528d4d110dfb). 

@teixeirak how quickly do you need it? We are aiming to release a new version in February. If it could wait, I can make sure that it is fixed in the revised code that @potterzot is working on. If you need it before then, I could add a temporary fix to the old code.

**Comment by teixeirak** [comment]
If a temporary fix to the old code would be fast, it may be worthwhile. I just submitted a progress report/ extension request to the Smithsonian Women's Committee, and its possible that they'll look at it. Of course, what's really important is having it right in the revised version.

**Comment by dlebauer** [comment]
In principle it should be an easy fix. The difficult and daunting parts are
that it might not be easy, it might take some time to become familiar with
the old code and its hacks, and if we touch the code other errors might pop
up. The new version should make all of these issues much less of an issue
because we are cleaning up the quagmire of hacks. Thus my recommendation is
that unless it is absolutely essential, we should stay focused on the
updated version.

**Comment by teixeirak** [comment]
Ok.

On Dec 31, 2015, at 3:22 PM, David LeBauer wrote:

In principle it should be an easy fix. The difficult and daunting parts are
that it might not be easy, it might take some time to become familiar with
the old code and its hacks, and if we touch the code other errors might pop
up. The new version should make all of these issues much less of an issue
because we are cleaning up the quagmire of hacks. Thus my recommendation is
that unless it is absolutely essential, we should stay focused on the
updated version.

On Thu, Dec 31, 2015 at 10:40 AM, Kristina Anderson-Teixeira <
notifications@github.com<mailto:notifications@github.com>> wrote:

> If a temporary fix to the old code would be fast, it may be worthwhile. I
> just submitted a progress report/ extension request to the Smithsonian
> Women's Committee, and its possible that they'll look at it. Of course,
> what's really important is having it right in the revised version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebimodeling/ghgvc/issues/72#issuecomment-168233652>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/ebimodeling/ghgvc/issues/72#issuecomment-168242073>.


Kristina J. Anderson-Teixeira
Ecologist, Leader of CTFS-ForestGEO Ecosystems & Climate Initiative
Smithsonian Institution
Smithsonian Conservation Biology Institute
1500 Remount Rd.; Front Royal, VA 22630 USA
1-540-635-6546 | teixeirak@si.edu<mailto:teixeirak@si.edu>
www.ctfs.si.edu/group/Ecosystems+and+Climate<http://www.ctfs.si.edu/group/Ecosystems+and+Climate>
klamath-climate-and-fire.net<http://klamath-climate-and-fire.net>

**Comment by teixeirak** [comment]
This issue appears to be solved in the updated version. Thank you.
