### ISSUE TITLE
fix bug of ecosystems appearing in water

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#83]
Clicking on bodies of water, including in the middle of the ocean, commonly results in ecosystem options being listed (see example images). Please fix.
![water biomes](https://cloud.githubusercontent.com/assets/6355854/17866256/d8e89706-6873-11e6-8058-7878f13a5337.png)
![water biomes2](https://cloud.githubusercontent.com/assets/6355854/17866255/d8e72ab0-6873-11e6-8f5f-f33659d199f7.png)

**Comment by potterzot** [comment]
Either this got partially fixed along the recent changes, or was only the case when you've previously clicked somewhere else, and the previous biome data is still available. Regardless, should be completely fixed as of commit 7f670e0. 

It might be good to add some kind of "no biomes available." notice so that it doesn't seem like nothing is happening.
