### ISSUE TITLE
Add link to pdf with ecosystem info

### ISSUE THREAD

**Issue by teixeirak** [ebimodeling/ghgvc#87]
I'd like to provide info on each ecosystem type to the users. This will be in the form of .pdf documents for each ecosystem type. 

@potterzot - Following each ecosystem name (next to the edit link), could you please create an information icon that will link to .pdfs describing the ecosystem type? This will refer to the location-specific assignment of a vegetation type to an ecosystem type/ "biome"; for example, "Broadleaf evergreen forest" would link to T1 in Koppen zone Af). 

@ValentineHerr and I are working on creating these .pdfs, but for now a blank .pdf or error message is fine.

**Comment by potterzot** [comment]
I've added a 'link', and there are a pdf icon in assets/images/, but they aren't showing up for some reason. I could probably get this together with another hour or less of work, but might not get the chance tomorrow, so dropping this note here.

This is probably a super easy fix. The line adding the link is in [workflows.js](https://github.com/ebimodeling/ghgvc/blob/development/app/assets/javascripts/workflows.js), line 174. Note that also the actual link to the pdf file has to be added, which will probably depend on a string combination of the biome name and the rest of the file. Easiest would be to make it something standard like "Shrub_info.pdf", so that the file name matches the ecosystem name.

**Comment by teixeirak** [comment]
Thanks!

We will name the files (all .pdf) T1-T13, S1-S6, etc. For now, we can substitute with a file saying "Information on this ecosystem type coming soon."

**Comment by potterzot** [comment]
I have the pdf icons added to the app, but the logic that points each specific biome code to the appropriate pdf hasn't been added. I will focus on that next.

**Comment by teixeirak** [comment]
The pdfs are now ready and in Box: https://app.box.com/files/0/f/11583247111/Ecosystem_fact_sheets

**Comment by teixeirak** [comment]
Note that the page currently resets if user clicks on one these links; therefore I am marking this as an essential issue.

**Comment by potterzot** [comment]
Works!

**Comment by teixeirak** [comment]
Thanks! Could you please provide instructions on how to update the pdf?

**Comment by potterzot** [comment]
The pdfs can be updated by just copying new ones to [assets/ecosystem_fact_sheets](https://github.com/ebimodeling/ghgvc/tree/master/app/assets/ecosystem_fact_sheets)

**Comment by dlebauer** [comment]
FYI there is an 'upload new file' on the page Nick linked to.
